# Generated by Django 3.2.6 on 2021-08-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='time_of_attendance',
            field=models.DateTimeField(null=True),
        ),
    ]
