# Generated by Django 3.2.6 on 2021-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_eventregistration_time_of_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='is_registration_approved',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=200, null=True),
        ),
    ]
