# Generated by Django 3.2.6 on 2021-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_eventregistration_is_registration_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='time_of_attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
