# Generated by Django 3.2.6 on 2021-08-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
