# Generated by Django 3.2.6 on 2021-08-28 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('detailed_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CONFERENCE', 'CONFERENCE'), ('SEMINAR', 'SEMINAR'), ('WORKSHOP', 'WORKSHOP')], max_length=200, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('is_attendance_open', models.BooleanField()),
                ('is_paid', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
