# Generated by Django 3.2.6 on 2021-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210828_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=200, null=True),
        ),
    ]
