# Generated by Django 3.2.6 on 2021-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.CharField(max_length=200, null=True)),
                ('support_number', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
