# Generated by Django 3.2.6 on 2021-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_supportcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportcontact',
            old_name='support_email',
            new_name='support_contact',
        ),
        migrations.RemoveField(
            model_name='supportcontact',
            name='support_number',
        ),
        migrations.AddField(
            model_name='supportcontact',
            name='contact_type',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('NUMBER', 'NUMBER')], max_length=200, null=True),
        ),
    ]
