# Generated by Django 3.2.6 on 2021-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20210830_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('1ST BANNER', '1ST BANNER'), ('2ND BANNER', '2ND BANNER'), ('3RD BANNER', '3RD BANNER')], max_length=200, null=True)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
