# Generated by Django 3.2.6 on 2021-09-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
