from django.urls import path
from . import views

urlpatterns = [
    path('dashboard', views.AdministratorDashboard.as_view(),
         name='administrator-dashboard'),
    path('events/create-new', views.CreateEvent.as_view(),
         name='create-event'),
    path('events/list', views.ListEvents.as_view(),
         name='list-events'),
    path('events/update/<int:event_id>/',
         views.UpdateEvent.as_view(), name='update-event'),
    path('events/delete/<int:event_id>', views.deleteEvent, name='delete-event'),
    path('members/list', views.ListMembers.as_view(),
         name='list-members'),
    path('members/delete/<int:member_id>',
         views.deleteMember, name='delete-member'),
    path('transactions', views.AllTransactions.as_view(), name='all-transactions'),
    path('transactions/transaction/set-status/<int:transaction_id>',
         views.SetTransactionStatus.as_view(), name='set-transaction-status'),
    path('events/event/<int:event_id>/reports',
         views.EventReports.as_view(), name='event-reports'),
    path('members/member/<int:member_id>/profile',
         views.MemberProfile.as_view(), name='member-profile'),
    path('support-contacts', views.SupportContacts.as_view(),
         name='list-members'),
    path('support-contact/delete/<int:contact_id>',
         views.deleteContact, name='delete-contact'),
    path('announcements', views.Announcement.as_view(),
         name='announcement'),
]
